# Generated by Django 5.1.3 on 2026-10-08 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderitem_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='address',
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
    ]
