# Generated by Django 5.1.3 on 2026-09-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='gst_number',
            field=models.CharField(default='', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
