# Generated by Django 5.1.3 on 2026-09-17 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'ADMIN'), ('manager', 'Manager'), ('seller', 'Seller'), ('user', 'User')], default='user', max_length=20),
        ),
    ]
